name: Branch Naming

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: read

jobs:
  check:
    uses: ArchonVII/github-workflows/.github/workflows/branch-naming.yml@v1
